# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MCMEstm2_2.ui'
#
# Created: Sat Dec 12 09:58:57 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1163, 771)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 771))
        MainWindow.setBaseSize(QtCore.QSize(1163, 771))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 232, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 116, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 155, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 232, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 232, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 116, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 155, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 232, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 116, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 232, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 116, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 155, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 116, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 116, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 232, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 232, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 232, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/calculator2-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setIconSize(QtCore.QSize(48, 48))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(610, 688))
        self.centralwidget.setMaximumSize(QtCore.QSize(610, 688))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setMinimumSize(QtCore.QSize(592, 670))
        self.groupBox_6.setMaximumSize(QtCore.QSize(592, 670))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_13 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_13.setMinimumSize(QtCore.QSize(531, 191))
        self.groupBox_13.setMaximumSize(QtCore.QSize(16777215, 191))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_13)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.dodaj_btn = QtGui.QPushButton(self.groupBox_13)
        self.dodaj_btn.setMinimumSize(QtCore.QSize(105, 30))
        self.dodaj_btn.setMaximumSize(QtCore.QSize(105, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Pencil_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dodaj_btn.setIcon(icon1)
        self.dodaj_btn.setObjectName(_fromUtf8("dodaj_btn"))
        self.gridLayout.addWidget(self.dodaj_btn, 2, 0, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.groupBox_13)
        self.textEdit.setEnabled(True)
        self.textEdit.setMinimumSize(QtCore.QSize(491, 121))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 3)
        self.checkBox_generator = QtGui.QCheckBox(self.groupBox_13)
        self.checkBox_generator.setObjectName(_fromUtf8("checkBox_generator"))
        self.gridLayout.addWidget(self.checkBox_generator, 2, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_13)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_8.setMinimumSize(QtCore.QSize(531, 70))
        self.groupBox_8.setMaximumSize(QtCore.QSize(16777215, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lineWyrazenie = QtGui.QLineEdit(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineWyrazenie.setFont(font)
        self.lineWyrazenie.setObjectName(_fromUtf8("lineWyrazenie"))
        self.verticalLayout_3.addWidget(self.lineWyrazenie)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.groupBox_11 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_11.setMinimumSize(QtCore.QSize(531, 115))
        self.groupBox_11.setMaximumSize(QtCore.QSize(16777215, 115))
        self.groupBox_11.setTitle(_fromUtf8(""))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.groupBox_12 = QtGui.QGroupBox(self.groupBox_11)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 10, 421, 91))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.line_P = QtGui.QLineEdit(self.groupBox_12)
        self.line_P.setObjectName(_fromUtf8("line_P"))
        self.gridLayout_7.addWidget(self.line_P, 1, 1, 1, 1)
        self.P_label = QtGui.QLabel(self.groupBox_12)
        self.P_label.setObjectName(_fromUtf8("P_label"))
        self.gridLayout_7.addWidget(self.P_label, 1, 0, 1, 1)
        self.M_label = QtGui.QLabel(self.groupBox_12)
        self.M_label.setObjectName(_fromUtf8("M_label"))
        self.gridLayout_7.addWidget(self.M_label, 0, 0, 1, 1)
        self.line_M = QtGui.QLineEdit(self.groupBox_12)
        self.line_M.setObjectName(_fromUtf8("line_M"))
        self.gridLayout_7.addWidget(self.line_M, 0, 1, 1, 1)
        self.reset_btn = QtGui.QPushButton(self.groupBox_11)
        self.reset_btn.setGeometry(QtCore.QRect(460, 40, 95, 30))
        self.reset_btn.setMinimumSize(QtCore.QSize(95, 30))
        self.reset_btn.setMaximumSize(QtCore.QSize(95, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Cancel_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset_btn.setIcon(icon2)
        self.reset_btn.setObjectName(_fromUtf8("reset_btn"))
        self.verticalLayout.addWidget(self.groupBox_11)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_7.setMinimumSize(QtCore.QSize(531, 170))
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.wyniki_groupBox_2 = QtGui.QGroupBox(self.groupBox_7)
        self.wyniki_groupBox_2.setGeometry(QtCore.QRect(10, 10, 421, 111))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.wyniki_groupBox_2.setFont(font)
        self.wyniki_groupBox_2.setObjectName(_fromUtf8("wyniki_groupBox_2"))
        self.Estymator_lbl_2 = QtGui.QLabel(self.wyniki_groupBox_2)
        self.Estymator_lbl_2.setGeometry(QtCore.QRect(10, 20, 171, 20))
        self.Estymator_lbl_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Estymator_lbl_2.setObjectName(_fromUtf8("Estymator_lbl_2"))
        self.Wynik_srednia = QtGui.QLabel(self.wyniki_groupBox_2)
        self.Wynik_srednia.setGeometry(QtCore.QRect(200, 20, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Wynik_srednia.setFont(font)
        self.Wynik_srednia.setAlignment(QtCore.Qt.AlignCenter)
        self.Wynik_srednia.setObjectName(_fromUtf8("Wynik_srednia"))
        self.odchyl_lbl_2 = QtGui.QLabel(self.wyniki_groupBox_2)
        self.odchyl_lbl_2.setGeometry(QtCore.QRect(10, 50, 171, 21))
        self.odchyl_lbl_2.setObjectName(_fromUtf8("odchyl_lbl_2"))
        self.Wynik_odchylenie = QtGui.QLabel(self.wyniki_groupBox_2)
        self.Wynik_odchylenie.setGeometry(QtCore.QRect(200, 50, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Wynik_odchylenie.setFont(font)
        self.Wynik_odchylenie.setAlignment(QtCore.Qt.AlignCenter)
        self.Wynik_odchylenie.setObjectName(_fromUtf8("Wynik_odchylenie"))
        self.Wynik_przedzil = QtGui.QLabel(self.wyniki_groupBox_2)
        self.Wynik_przedzil.setGeometry(QtCore.QRect(200, 80, 211, 21))
        font = QtGui.QFont()
        #font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Wynik_przedzil.setFont(font)
        self.Wynik_przedzil.setTextFormat(QtCore.Qt.AutoText)
        self.Wynik_przedzil.setAlignment(QtCore.Qt.AlignCenter)
        self.Wynik_przedzil.setObjectName(_fromUtf8("Wynik_przedzil"))
        self.przedzial_lbl_2 = QtGui.QLabel(self.wyniki_groupBox_2)
        self.przedzial_lbl_2.setGeometry(QtCore.QRect(10, 80, 171, 20))
        self.przedzial_lbl_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.przedzial_lbl_2.setObjectName(_fromUtf8("przedzial_lbl_2"))
        self.draw_btn = QtGui.QPushButton(self.groupBox_7)
        self.draw_btn.setGeometry(QtCore.QRect(460, 70, 95, 30))
        self.draw_btn.setMinimumSize(QtCore.QSize(95, 30))
        self.draw_btn.setMaximumSize(QtCore.QSize(95, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Edit_page_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.draw_btn.setIcon(icon3)
        self.draw_btn.setObjectName(_fromUtf8("draw_btn"))
        self.spinBox = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox.setGeometry(QtCore.QRect(20, 140, 42, 22))
        self.spinBox.setSpecialValueText(_fromUtf8(""))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.label_10 = QtGui.QLabel(self.groupBox_7)
        self.label_10.setGeometry(QtCore.QRect(70, 140, 271, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.oblicz_btn = QtGui.QPushButton(self.groupBox_7)
        self.oblicz_btn.setGeometry(QtCore.QRect(460, 20, 95, 30))
        self.oblicz_btn.setMinimumSize(QtCore.QSize(95, 30))
        self.oblicz_btn.setMaximumSize(QtCore.QSize(95, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Play_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.oblicz_btn.setIcon(icon4)
        self.oblicz_btn.setObjectName(_fromUtf8("oblicz_btn"))
        self.progressBar = QtGui.QProgressBar(self.groupBox_7)
        self.progressBar.setGeometry(QtCore.QRect(400, 140, 160, 20))
        self.progressBar.setMinimumSize(QtCore.QSize(160, 20))
        self.progressBar.setMaximumSize(QtCore.QSize(160, 20))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.label = QtGui.QLabel(self.groupBox_7)
        self.label.setGeometry(QtCore.QRect(400, 120, 171, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.groupBox_7)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1163, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuSelect_Window_Style = QtGui.QMenu(self.menuView)
        self.menuSelect_Window_Style.setObjectName(_fromUtf8("menuSelect_Window_Style"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 194, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 224, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 97, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 129, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 194, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 224, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 194, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 224, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 97, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 129, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 194, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 224, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 97, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 194, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 224, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 97, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 129, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 97, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(84, 97, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 194, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 194, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 194, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.statusbar.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.statusbar.setFont(font)
        self.statusbar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.statusbar.setAutoFillBackground(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_1 = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_1.sizePolicy().hasHeightForWidth())
        self.dockWidget_1.setSizePolicy(sizePolicy)
        self.dockWidget_1.setMinimumSize(QtCore.QSize(549, 688))
        self.dockWidget_1.setBaseSize(QtCore.QSize(549, 688))
        self.dockWidget_1.setFloating(False)
        self.dockWidget_1.setFeatures(QtGui.QDockWidget.DockWidgetClosable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget_1.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget_1.setObjectName(_fromUtf8("dockWidget_1"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents_2.setSizePolicy(sizePolicy)
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.line_2 = QtGui.QFrame(self.dockWidgetContents_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_4.addWidget(self.line_2)
        self.line = QtGui.QFrame(self.dockWidgetContents_2)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.mplhorizontalLayout = QtGui.QHBoxLayout()
        self.mplhorizontalLayout.setObjectName(_fromUtf8("mplhorizontalLayout"))
        self.mpl = MplWidget(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName(_fromUtf8("mpl"))
        self.mplhorizontalLayout.addWidget(self.mpl)
        self.verticalLayout_4.addLayout(self.mplhorizontalLayout)
        self.line_3 = QtGui.QFrame(self.dockWidgetContents_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_4.addWidget(self.line_3)
        self.dockWidget_1.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_1)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.toolBar.setIconSize(QtCore.QSize(24, 24))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpenM = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Folder_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenM.setIcon(icon5)
        self.actionOpenM.setObjectName(_fromUtf8("actionOpenM"))
        self.actionOpen_Variable_File = QtGui.QAction(MainWindow)
        self.actionOpen_Variable_File.setIcon(icon5)
        self.actionOpen_Variable_File.setObjectName(_fromUtf8("actionOpen_Variable_File"))
        self.actionExtract = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Save_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExtract.setIcon(icon6)
        self.actionExtract.setObjectName(_fromUtf8("actionExtract"))
        self.actionHelp = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Help_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon7)
        self.actionHelp.setMenuRole(QtGui.QAction.AboutQtRole)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Info_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon8)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionExit = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Exit_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon9)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionWindows_Style = QtGui.QAction(MainWindow)
        self.actionWindows_Style.setObjectName(_fromUtf8("actionWindows_Style"))
        self.actionMotif_Style = QtGui.QAction(MainWindow)
        self.actionMotif_Style.setObjectName(_fromUtf8("actionMotif_Style"))
        self.actionCDE_Style = QtGui.QAction(MainWindow)
        self.actionCDE_Style.setObjectName(_fromUtf8("actionCDE_Style"))
        self.actionCleanlooks_Style = QtGui.QAction(MainWindow)
        self.actionCleanlooks_Style.setObjectName(_fromUtf8("actionCleanlooks_Style"))
        self.actionPlastique_Style = QtGui.QAction(MainWindow)
        self.actionPlastique_Style.setObjectName(_fromUtf8("actionPlastique_Style"))
        self.actionGTK_Style = QtGui.QAction(MainWindow)
        self.actionGTK_Style.setObjectName(_fromUtf8("actionGTK_Style"))
        self.actionWindowsVista_Style = QtGui.QAction(MainWindow)
        self.actionWindowsVista_Style.setCheckable(False)
        self.actionWindowsVista_Style.setMenuRole(QtGui.QAction.TextHeuristicRole)
        self.actionWindowsVista_Style.setObjectName(_fromUtf8("actionWindowsVista_Style"))
        self.actionMacintosh = QtGui.QAction(MainWindow)
        self.actionMacintosh.setObjectName(_fromUtf8("actionMacintosh"))
        self.actionShow_Histogram = QtGui.QAction(MainWindow)
        self.actionShow_Histogram.setObjectName(_fromUtf8("actionShow_Histogram"))
        self.menuMenu.addAction(self.actionOpenM)
        self.menuMenu.addAction(self.actionOpen_Variable_File)
        self.menuMenu.addAction(self.actionExtract)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSelect_Window_Style.addAction(self.actionWindows_Style)
        self.menuSelect_Window_Style.addAction(self.actionWindowsVista_Style)
        self.menuSelect_Window_Style.addAction(self.actionMotif_Style)
        self.menuSelect_Window_Style.addAction(self.actionCDE_Style)
        self.menuSelect_Window_Style.addAction(self.actionCleanlooks_Style)
        self.menuSelect_Window_Style.addAction(self.actionPlastique_Style)
        self.menuSelect_Window_Style.addAction(self.actionGTK_Style)
        self.menuSelect_Window_Style.addAction(self.actionMacintosh)
        self.menuView.addAction(self.menuSelect_Window_Style.menuAction())
        self.menuView.addAction(self.actionShow_Histogram)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpenM)
        self.toolBar.addAction(self.actionOpen_Variable_File)
        self.toolBar.addAction(self.actionExtract)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.dodaj_btn, self.lineWyrazenie)
        MainWindow.setTabOrder(self.lineWyrazenie, self.line_M)
        MainWindow.setTabOrder(self.line_M, self.line_P)
        MainWindow.setTabOrder(self.line_P, self.spinBox)
        MainWindow.setTabOrder(self.spinBox, self.oblicz_btn)
        MainWindow.setTabOrder(self.oblicz_btn, self.draw_btn)
        MainWindow.setTabOrder(self.draw_btn, self.reset_btn)
        MainWindow.setTabOrder(self.reset_btn, self.textEdit)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MCM Estymator", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Data", None))
        self.groupBox_13.setTitle(_translate("MainWindow", "Variables", None))
        self.dodaj_btn.setText(_translate("MainWindow", "Add variable", None))
        self.checkBox_generator.setText(_translate("MainWindow", "Wichmann-Hill generator", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Model", None))
        self.lineWyrazenie.setPlaceholderText(_translate("MainWindow", "Enter the model as an expresion", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Parameters", None))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setItalic(True)
        self.line_P.setFont(font)
        self.line_P.setPlaceholderText(_translate("MainWindow", "Enter The Coverage Probability value as number in percentage.", None))
        self.P_label.setText(_translate("MainWindow", "       P  =  ", None))
        self.M_label.setText(_translate("MainWindow", "       M  =", None))
        self.line_M.setFont(font)
        self.line_M.setPlaceholderText(_translate("MainWindow", "Enter number of the Monte Carlo trials", None))
        self.reset_btn.setText(_translate("MainWindow", "Reset", None))
        self.wyniki_groupBox_2.setTitle(_translate("MainWindow", "Results", None))
        self.Estymator_lbl_2.setText(_translate("MainWindow", "The best estimate value:", None))
        self.Wynik_srednia.setText(_translate("MainWindow", "0.0", None))
        self.odchyl_lbl_2.setText(_translate("MainWindow", "Standard uncertainty value:", None))
        self.Wynik_odchylenie.setText(_translate("MainWindow", "0.0", None))
        self.Wynik_przedzil.setText(_translate("MainWindow", "0.0  0.0", None))
        self.przedzial_lbl_2.setText(_translate("MainWindow", "Coverage interval values:", None))
        self.draw_btn.setText(_translate("MainWindow", "Draw", None))
        self.label_10.setText(_translate("MainWindow", "Number of significant decimal digits", None))
        self.oblicz_btn.setText(_translate("MainWindow", "Calculate", None))
        self.label.setText(_translate("MainWindow", "Calculation progress", None))
        self.menuMenu.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuSelect_Window_Style.setTitle(_translate("MainWindow", "Select Window Style", None))
        self.dockWidget_1.setWindowTitle(_translate("MainWindow", "Histogram", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionOpenM.setText(_translate("MainWindow", "Open Model File", None))
        self.actionOpenM.setStatusTip(_translate("MainWindow", "Opens a Model definition file", None))
        self.actionOpenM.setShortcut(_translate("MainWindow", "Ctrl+M", None))
        self.actionOpen_Variable_File.setText(_translate("MainWindow", "Open Variable File", None))
        self.actionOpen_Variable_File.setShortcut(_translate("MainWindow", "Ctrl+V", None))
        self.actionExtract.setText(_translate("MainWindow", "Extract data to File", None))
        self.actionExtract.setStatusTip(_translate("MainWindow", "Extracts the data computed into a file ", None))
        self.actionExtract.setShortcut(_translate("MainWindow", "Ctrl+E", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionExit.setText(_translate("MainWindow", "Exit Application", None))
        self.actionExit.setToolTip(_translate("MainWindow", "Click to exit the Application", None))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exits the Application", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionWindows_Style.setText(_translate("MainWindow", "Windows Style", None))
        self.actionMotif_Style.setText(_translate("MainWindow", "Motif Style", None))
        self.actionCDE_Style.setText(_translate("MainWindow", "CDE Style", None))
        self.actionCleanlooks_Style.setText(_translate("MainWindow", "Cleanlooks Style", None))
        self.actionPlastique_Style.setText(_translate("MainWindow", "Plastique Style", None))
        self.actionGTK_Style.setText(_translate("MainWindow", "GTK + Style", None))
        self.actionWindowsVista_Style.setText(_translate("MainWindow", "WindowsVista Style", None))
        self.actionMacintosh.setText(_translate("MainWindow", "Macintosh", None))
        self.actionShow_Histogram.setText(_translate("MainWindow", "Show Histogram", None))

from mplwidget import MplWidget
import icons_rc
